block('share-OC')({
    content: () => [
        
            {
                elem:'title',
                tag:'h6',
                content:'Поделиться:'
            },
            {
                elem:'icons',
                content:[
                    {
                        elem:'whassup-url',
                        tag:'a',
                        attrs:{
                            href:'#'
                        },
                        content:{
                            elem:'whassup-icon',
                            tag:'img',
                            attrs:{
                                src:'/img/share-OC/whassup_blue.svg',
                                title:'whatsapp-icon'
                            },
                        }
                    },
                    {
                        elem:'vk-url',
                        tag:'a',
                        attrs:{
                            href:'#'
                        },
                        content:{
                            elem:'vk-icon',
                            tag:'img',
                            attrs:{
                                src:'/img/share-OC/vk_blue.svg',
                                title:'vk-icon'
                            },
                        }
                    },
                    {
                        elem:'telegram-url',
                        tag:'a',
                        attrs:{
                            href:'#'
                        },
                        content:{
                            elem:'telegram-icon',
                            tag:'img',
                            attrs:{
                                src:'/img/share-OC/telegram_blue.svg',
                                title:'telegram-icon'
                            },
                        }
                    },
                    {
                        elem:'twitter-url',
                        tag:'a',
                        attrs:{
                            href:'#'
                        },
                        content:{
                            elem:'twitter-icon',
                            tag:'img',
                            attrs:{
                                src:'/img/share-OC/twitter_blue.svg',
                                title:'twitter-icon'
                            },
                        }
                    },
                    {
                        elem:'facebook-url',
                        tag:'a',
                        attrs:{
                            href:'#'
                        },
                        content:{
                            elem:'facebook-icon',
                            tag:'img',
                            attrs:{
                                src:'/img/share-OC/facebook_blue.svg',
                                title:'facebook-icon'
                            },
                        }
                    },
                    {
                        elem:'share-url',
                        tag:'a',
                        attrs:{
                            href:'#'
                        },
                        content:{
                            elem:'share-icon',
                            tag:'img',
                            attrs:{
                                src:'/img/share-OC/share_blue.svg',
                                title:'share-icon'
                            },
                        }
                    },
                ]
            }
        
    ]
});
