block('profile-OC').elem('settings')({
    content: () => [
        
        {
            elem:'settings-top',
            content:[
                {
                    elem:'settings-avatar',
                    content:[
                        {   
                            elem:'settings-img',
                            content:{
                                tag:'img',
                                attrs:{
                                    src:'/img/profile-OC/avatar-plug.png'
                                }
                            }
                            
                        },
                        {
                            
                            tag:'a',
                            content:{
                                elem:'change-avatar'
                            }
                        }
                    ]
                },
                {
                    elem:'settings-data',
                    content:[
                        {
                            elem:'settings-name',
                            tag:'h6',
                            content:'Михаил Зубенко Петрович'
                        },
                        {
                            elem:'settings-info',
                            tag:'span',
                            content:[
                                {
                                    elem:'decided',
                                    content:[
                                        {
                                            tag:'span',
                                            content:'Проблем решено'
                                        }
                                        ,
                                        '12'
                                        ,
                                    ]
                                },
                                {
                                    elem:'total-scores',
                                    content:[
                                        {
                                            tag:'span',
                                            content:'Баллов платформы'
                                        }
                                        ,
                                        '12334'
                                        ,
                                    ]
                                }
                                
                            ]
                        }
                    ]
                }
            ]
        },
        {
            elem:'settings-body',
            content:{
                cls:'row',
                content:[
                    {   
                        block:'profile-OC',
                        elem:'col',
                        cls:'col-xl-4',
                        content:[
                            {   
                                block:'profile-OC',
                                elem:'settings-title',
                                tag:'span',
                                content:'Имя'
                            },
                            {   
                                block:'profile-OC',
                                elem:'settings-quot',
                                tag:'span',
                                content:'*'
                            },
                            {   
                                
                                block:'input-OC',
                                mix:{
                                    block:'profile-OC',
                                    elem:'settings-input'
                                },
                                content:[
                                    {
                                        placeholder:'Введите ваше имя'
                                    }
                                ]
                            }
                        ]
                    },
                    {   
                        block:'profile-OC',
                        elem:'col',
                        cls:'col-xl-4',
                        content:[
                            {   
                                block:'profile-OC',
                                elem:'settings-title',
                                tag:'span',
                                content:'Фамилия'
                            },
                            {   
                                block:'profile-OC',
                                elem:'settings-quot',
                                tag:'span',
                                content:'*'
                            },
                            {   
                                
                                block:'input-OC',
                                mix:{
                                    block:'profile-OC',
                                    elem:'settings-input'
                                },
                                content:[
                                    {
                                        placeholder:'Введите вашу фамилию'
                                    }
                                ]
                            }
                        ]
                    },
                    {   
                        block:'profile-OC',
                        elem:'col',
                        cls:'col-xl-4',
                        content:[
                            {   
                                block:'profile-OC',
                                elem:'settings-title',
                                tag:'span',
                                content:'Пол'
                            },
                            {   
                                block:'profile-OC',
                                elem:'settings-quot',
                                tag:'span',
                                content:'*'
                            },
                            {   
                                
                                block:'select-OC',
                                mix:{
                                    block:'profile-OC',
                                    elem:'settings-input'
                                },
                                content:[
                                    {
                                        placeholder:'Введите ваш пол'
                                    }
                                ]
                            }
                        ]
                    },
                    {   
                        block:'profile-OC',
                        elem:'col',
                        cls:'col-xl-4',
                        content:[
                            {   
                                block:'profile-OC',
                                elem:'settings-title',
                                tag:'span',
                                content:'Дата рождения'
                            },
                            {   
                                block:'profile-OC',
                                elem:'settings-quot',
                                tag:'span',
                                content:'*'
                            },
                            {   
                                
                                block:'input-OC',
                                mix:{
                                    block:'profile-OC',
                                    elem:'settings-input'
                                },
                                content:[
                                    {
                                        placeholder:'Введите ваше дату рождения'
                                    }
                                ]
                            }
                        ]
                    },
                    {   
                        block:'profile-OC',
                        elem:'col',
                        cls:'col-xl-4',
                        content:[
                            {   
                                block:'profile-OC',
                                elem:'settings-title',
                                tag:'span',
                                content:'Телефон'
                            },
                            {   
                                block:'profile-OC',
                                elem:'settings-quot',
                                tag:'span',
                                content:'*'
                            },
                            {   
                                
                                block:'input-OC',
                                mix:{
                                    block:'profile-OC',
                                    elem:'settings-input'
                                },
                                content:[
                                    {
                                        placeholder:'+7('
                                    }
                                ]
                            }
                        ]
                    },
                    {   
                        block:'profile-OC',
                        elem:'col',
                        cls:'col-xl-4',
                        content:[
                            {   
                                block:'profile-OC',
                                elem:'settings-title',
                                tag:'span',
                                content:'E-mail'
                            },
                            {   
                                block:'profile-OC',
                                elem:'settings-quot',
                                tag:'span',
                                content:'*'
                            },
                            {   
                                
                                block:'input-OC',
                                mix:{
                                    block:'profile-OC',
                                    elem:'settings-input'
                                },
                                content:[
                                    {
                                        placeholder:'Введите вашу электронную почту'
                                    }
                                ]
                            }
                        ]
                    },
                    {   
                        block:'profile-OC',
                        elem:'col',
                        cls:'col-xl-4',
                        content:[
                            {   
                                block:'profile-OC',
                                elem:'settings-title',
                                tag:'span',
                                content:'Город'
                            },
                            {   
                                block:'profile-OC',
                                elem:'settings-quot',
                                tag:'span',
                                content:'*'
                            },
                            {   
                                
                                block:'input-OC',
                                mix:{
                                    block:'profile-OC',
                                    elem:'settings-input'
                                },
                                content:[
                                    {
                                        placeholder:'Введите ваш адрес'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        },
        {
            elem:'settings-bottom',
            content:{
                elem:'settings-button',
                mix:{block:'button-OC'},
                tag:'button',
                content:'Сохранить'
            }
        }
        
    ]
});