({
    shouldDeps: [
        {
            elems:['menu']
        },
        {
            elems:['icon-folder']
        },
        {
            elems:['icon-settings']
        },
        {
            elems:['icon-paperclip']
        },
        {
            elems:['icon-star']
        },
        {
            elems:['cards']
        },
        {
            elems:['in-work']
        },
        {
            elems:['card']
        },
        {
            elems:['archive']
        },
        {
            elems:['card-archive']
        },
        'status'
    ]
});