({
    shouldDeps: [
        {
            elems:['menu']
        },
        {
            elems:['icon-folder']
        },
        {
            elems:['icon-settings']
        },
        {
            elems:['icon-paperclip']
        },
        {
            elems:['icon-star']
        },
        {
            elems:['cards']
        },
        {
            elems:['in-work']
        },
        {
            elems:['card']
        },
        {
            elems:['archive']
        },
        {
            elems:['card-archive']
        },
        'status',
        {
            elems:['settings']
        },
        'input-OC',
        'select-OC',
        {
            elems:['scores']
        },
        'button-OC',
        {
            elems:['scores-row']
        },
        
    ]
});